#Assignment 4: Numpy

##Sagar Matur
GO_STP_6290

1.	Import the numpy package under the name np and Print the numpy version and the configuration 

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2.	Create a null vector of size 10

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3.	Create Simple 1-D array and check type and check data types in array

In [ ]:
a = np.array([1, 8, 15, 24, 58])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


4.	How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
print("Number of dimension is: ",a.ndim)
print("bytes per element is: ",a.nbytes)
print("Total bytes of memory used is: ",a.itemsize)

Number of dimension is:  1
bytes per element is:  40
Total bytes of memory used is:  8


5.	Create a null vector of size 10 but the fifth value which is 1

In [ ]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6.	Create a vector with values ranging from 10 to 49

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7.	Reverse a vector (first element becomes last)

In [ ]:
#Reversing the vector 'a'
np.flip(a)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

8.	Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
mat = np.arange(9).reshape(3,3)
print("The 3*3 matrix is: \n", mat)

The 3*3 matrix is: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


9.	Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
nz = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(nz)

(array([0, 1, 4]),)

10.	Create a 3x3 identity matrix

In [ ]:
iden_matrix = np.identity(3)
print("A 3*3 identity matrix is: \n",iden_matrix)

A 3*3 identity matrix is: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11.	Create a 3x3x3 array with random values

In [ ]:
ran = np.random.random((3,3,3))
print(ran)

[[[0.54396479 0.91993945 0.92499455]
  [0.14745723 0.81349796 0.16156739]
  [0.41597632 0.43531109 0.78652708]]

 [[0.41074776 0.78447068 0.48096702]
  [0.7665426  0.45850876 0.12338893]
  [0.45891767 0.4065453  0.77256172]]

 [[0.13802048 0.97572342 0.48148952]
  [0.16786908 0.90729511 0.66933312]
  [0.10785903 0.18598071 0.94130801]]]


12.	Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
ran2 = np.random.random((10,10))
print(ran2)
print("The minimum value is: ",ran2.min())
print("The maximum value is: ",ran2.max())

[[0.73324643 0.91557972 0.96802564 0.33237525 0.49862079 0.57113772
  0.17522337 0.12075285 0.01917447 0.35098037]
 [0.64473419 0.02726448 0.86556631 0.24904008 0.06304835 0.28275609
  0.2388372  0.30855713 0.061014   0.85344631]
 [0.90164225 0.61764922 0.15944303 0.75015556 0.23951059 0.4974772
  0.98720434 0.05268896 0.74082831 0.65591899]
 [0.87456844 0.91847835 0.14916926 0.46906626 0.76268603 0.08095363
  0.36825505 0.95379092 0.56891659 0.44109642]
 [0.58696793 0.45489059 0.95525226 0.4957642  0.26342495 0.43821743
  0.4759156  0.42893995 0.78797816 0.42762879]
 [0.26985511 0.26956013 0.00249735 0.05402843 0.78652546 0.11561372
  0.96680608 0.58203594 0.32557632 0.35706711]
 [0.09879263 0.88634235 0.9442484  0.35574913 0.86114385 0.72217298
  0.43571198 0.00751592 0.02720109 0.99840988]
 [0.76600837 0.70125185 0.46842369 0.76807779 0.28766088 0.33835638
  0.15137573 0.94730825 0.52498181 0.03907665]
 [0.63306134 0.80517655 0.68066739 0.08670823 0.48063512 0.00827629
  0.62473105 

13.	Create a random vector of size 30 and find the mean value

In [ ]:
ran3 = np.random.random(30)
print("Size of the vector is: ",ran3.size)
print("The mean is: ", ran3.mean())

Size of the vector is:  30
The mean is:  0.5234993746936027


14.	Create a 2d array with 1 on the border and 0 inside

In [ ]:
ar = np.ones((6,6))
ar[1:-1,1:-1] = 0
print(ar)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


15.	How to add a border (filled with 0's) around an existing array?

In [ ]:
ar = np.pad(ar, pad_width=1, mode='constant', constant_values=0)
print(ar)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


16.	How to Accessing/Changing specific elements, rows, columns, etc in Numpy array? \\
Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]] \\
Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20


In [ ]:
ar1=np.array([[ 1, 2, 3, 4, 5, 6, 7],[ 8, 9, 10, 11, 12, 13, 14]])
print(ar1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
print(ar1[1,5]) #Get 13
print(ar1[0])    #Get the first row only
print(ar1[:,2])  #Get the third column
print(ar1[0][1:7:2]) #Get [2,4,6]
ar1[1,5]=20          #Replace 13 by 20    
print(ar1)

13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


17.	How to Convert a 1D array to a 2D array with 2 rows

In [ ]:
ar = np.arange(10)
print("The 1-D array is: ",ar)
print("The 2-D array is: \n",ar.reshape(2,5))

The 1-D array is:  [0 1 2 3 4 5 6 7 8 9]
The 2-D array is: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


18.	Create the following pattern without hardcoding. Use only numpy functions and the below input array a. \\
Input: \\
a = np.array([1,2,3]) \\
Desired Output: \\
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [ ]:
a = np.array([1,2,3])
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

19.	Write a program to show how Numpy taking less memory compared to Python List?

In [ ]:

# importing system module
import sys
  
# declaring a list of 1000 elements 
l= range(1000)
  
# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(l))
  
# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(l)*len(l))
  
# declaring a Numpy array of 1000 elements 
n= np.arange(1000)
  
# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",n.itemsize)
  
# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",n.size*n.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


20.	Write a program to show how Numpy taking less time compared to Python List?

In [ ]:
import time

# capturing time before the multiplication of Python lists
initialTime = time.time()
  
# multiplying  elements of both the lists and stored in another list
List1 = [(a * b) for a, b in zip(range(10000), range(10000))]
   
# calculating execution time
print("Time taken by Lists to perform multiplication:", 
      (time.time() - initialTime),
      "seconds")
# capturing time before the multiplication of Numpy arrays
initialTime = time.time()
  
# multiplying  elements of both the Numpy arrays and stored in another Numpy array 
array1 = np.arange(10000) * np.arange(10000)
# calculating execution time 
print("Time taken by NumPy Arrays to perform multiplication:",
      (time.time() - initialTime),
      "seconds")

Time taken by Lists to perform multiplication: 0.0017397403717041016 seconds
Time taken by NumPy Arrays to perform multiplication: 0.003474712371826172 seconds
